let points = [];
let pointCount = 100;
let pointBuffer = 50;

let delaunay;

function setup() {
  createCanvas(windowWidth, windowHeight);
  
  for(let i = 0; i < pointCount; i++){
    points.push(createVector(random(pointBuffer,width-pointBuffer),random(pointBuffer,height-pointBuffer)));
  }
  
  //Calculate Delaunay triangles for this set of points
  delaunay = calcDelaunay(points);
}

function draw() {
  background(20);
  
  updatePoints(points);
  delaunay = calcDelaunay(points);
  
  //Draw Points
  push();
  //loop through all elements in the points[] array, considering each one as a variable called v
  for(let v of points){
    noStroke();
    fill(230);
    circle(v.x,v.y,5);
  }
  pop();
  
  //Draw Triangles
  push();
  //loop through every third element in the triangles array generated by d3's Delaunay() function
  //https://d3js.org/d3-delaunay/delaunay
  for (let i = 0; i < delaunay.triangles.length; i+= 3){
    //Read the indices of each triangle vertex from delaunay.triangles
    let pointA = 2 * delaunay.triangles[i];
    let pointB = 2 * delaunay.triangles[i + 1];
    let pointC = 2 * delaunay.triangles[i + 2];
    
    strokeWeight(1);
    noFill();
    stroke(180);
    
    //Draw a triangle with vertices at the vertex locations in delaunay.points, using the indices read above ^
    triangle(delaunay.points[pointA], delaunay.points[pointA + 1],
            delaunay.points[pointB], delaunay.points[pointB + 1],
            delaunay.points[pointC], delaunay.points[pointC + 1])
  }
  pop();
}

function calcDelaunay(points){
  //Convert from a list of p5.Vectors to a single long array of values storing the x and y location of each point in order,
  // e.g. [x0,y0,x1,y1,x2,y2...] etc
  let pointsArray = [];
  for(let v of points){
    pointsArray.push(v.x);
    pointsArray.push(v.y);
  }
  //create a new set of triangles and points using the new pointsArray using d3's Delaunay() function, and return it
  return new d3.Delaunay(pointsArray);
}

function updatePoints(pointArray){
  for(let i = 0; i < pointArray.length; i++){
    let randDir = createVector(random(-1,1),random(-1,1));
    randDir.normalize();
    pointArray[i].add(randDir);
  }
    
}